# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e87cdc8a-c7ec-4866-b4d1-f52d1afdf82b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e87cdc8a-c7ec-4866-b4d1-f52d1afdf82b".device = "/dev/disk/by-uuid/e87cdc8a-c7ec-4866-b4d1-f52d1afdf82b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4BB5-6110";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-58e3c917-e5d1-4406-a6fa-acf832a930e0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
