# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-5cb4bb5b-c779-4334-acb5-eae46dd78bcb";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5cb4bb5b-c779-4334-acb5-eae46dd78bcb".device = "/dev/disk/by-uuid/5cb4bb5b-c779-4334-acb5-eae46dd78bcb";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9FC4-AC5E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-4e59cf21-e428-4754-8178-4630e943a4d0";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
